import type { StoredAnswers } from '@sage-burner/shared'
import type { SQL } from 'drizzle-orm'
import type { AnySQLiteColumn, SQLiteColumn } from 'drizzle-orm/sqlite-core'

import {
  accountRoles,
  applicationStatuses,
  notificationCategories,
  effortLevels,
  eventOptionKinds,
  formQuestionTypes,
  ICON_TYPES,
  mealRoles,
  mealSlotKinds,
  paymentStatuses,
  placeColors,
  tickBoxRequired,
} from '@sage-burner/shared'
import { sql } from 'drizzle-orm'
import {
  blob,
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core'

/**
 * `column` is a fixed-width 24-hour `HH:MM`.
 *
 * Shape only, and fixed width is the point: the order CHECK above compares these
 * as strings, which is sound while `09:00` cannot also arrive as `9:00`.
 */
const isClockTime = (column: SQLiteColumn): SQL =>
  sql`${column} glob '[0-2][0-9]:[0-5][0-9]' and cast(substr(${column}, 1, 2) as integer) < 24`

/**
 * `column` is a fixed-width `YYYY-MM-DD` date, or null.
 *
 * The date-ordering CHECKs compare these as strings, which is only sound
 * because the width is fixed — a raw insert of `'2026-1-2'` sorts wrong and
 * would slip past them. Same reasoning as `oneOf`: the constraint exists for
 * writes that do not come through the API, so it has to hold on its own.
 *
 * Shape only. It does not reject `2026-02-30`; `z.iso.date()` does that at the
 * API boundary.
 */
const isIsoDate = (column: SQLiteColumn): SQL =>
  sql`${column} is null or ${column} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`

/**
 * `column IN (...)`, built from a vocabulary in `@sage-burner/shared`.
 *
 * Drizzle's `{ enum: [...] }` only narrows the TypeScript type — it emits no
 * constraint, so without this a bad value reaching the database by any path
 * other than the API would be stored happily. Generating the CHECK from the
 * same constant the API validates against is what actually keeps the two from
 * drifting.
 */
const oneOf = (column: SQLiteColumn, values: readonly string[]): SQL => {
  // Must be `sql.raw`, not interpolation: `sql`${value}`` produces a bound
  // parameter, and a `?` placeholder inside a CHECK constraint is meaningless
  // DDL. These values are compile-time constants from our own source, but the
  // quote-doubling keeps that from being load-bearing.
  const literals = values.map((value) => `'${value.replaceAll("'", "''")}'`).join(', ')
  return sql`${column} in (${sql.raw(literals)})`
}

/**
 * `CHECK`s for the tick-box rule, generated from `tickBoxRequired` rather than
 * spelled out again in SQL.
 *
 * The rule is that `agreement` must be required and `checkbox` must not. Writing
 * it here by hand would leave the database as the one enforcement site that does
 * *not* derive from the shared function — so adding a fifth type with a fixed
 * `required` would be enforced by the schema, the `UPDATE` and the editor, and
 * silently not by the database, which is the exact gap the API-level version of
 * this rule already fell into once.
 *
 * `sql.raw` for the same reason as `oneOf`: a bound parameter is meaningless DDL.
 * The values come from our own vocabulary, and the quote-doubling keeps that from
 * being load-bearing.
 */
const tickBoxChecks = (table: { type: SQLiteColumn; required: SQLiteColumn }) =>
  formQuestionTypes.flatMap((type) => {
    const must = tickBoxRequired(type)
    if (must === undefined) return []

    const literal = `'${type.replaceAll("'", "''")}'`

    return [
      check(
        `form_question_${type}_required_check`,
        sql`${table.type} <> ${sql.raw(literal)} or ${table.required} = ${sql.raw(must ? '1' : '0')}`,
      ),
    ]
  })

/**
 * Database schema.
 *
 * Conventions:
 * - Ids are TEXT UUIDs generated by the application, never autoincrementing
 *   integers — an id in a URL should leak neither record counts nor the
 *   existence of neighbours.
 * - Dates and timestamps are TEXT in ISO 8601 form, exactly as they cross the
 *   API boundary. SQLite has no date type, and storing the wire format means
 *   there is no conversion layer to get wrong (and the file stays readable).
 * - Timestamps are supplied by the application rather than by SQL defaults, so
 *   tests can inject a fixed clock.
 * - Enum columns are TEXT constrained by the vocabularies in
 *   `@sage-burner/shared`, so the database and the API cannot drift apart.
 */

/**
 * What this deployment calls itself.
 *
 * One row, and the CHECK is what makes that true rather than a convention:
 * a second row cannot be inserted, so no read has to decide which is
 * authoritative and no write has to find the right one. The migration seeds it,
 * so every read finds it there.
 */
export const installation = sqliteTable(
  'installation',
  {
    id: text('id').notNull(),
    title: text('title').notNull(),
    /**
     * The VAPID keypair browser push is signed with, minted on first use.
     *
     * In the database rather than the environment so `docker compose up` stays
     * sufficient — the same argument #59 makes for `SESSION_SECRET`, and it applies
     * more easily here because push is optional: an installation that never turns
     * it on never mints a key. Rotating the pair invalidates every existing
     * subscription, which is why it is minted once and kept rather than derived.
     */
    vapid_public_key: text('vapid_public_key'),
    vapid_private_key: text('vapid_private_key'),
    /**
     * The build this installation last booted on, so a redeploy can be noticed (#259).
     *
     * Null until the first boot that looks, which records without announcing: there is
     * no previous version for it to be new against.
     */
    last_build_sha: text('last_build_sha'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    check('installation_singleton_check', sql`${table.id} = 'installation'`),
    check('installation_title_check', sql`length(trim(${table.title})) > 0`),
  ],
)

/** The id of the one `installation` row. */
export const INSTALLATION_ID = 'installation'

/**
 * The icon an installed copy of this app wears on a home screen (#256).
 *
 * Its own table rather than a column on `installation`, so the row every page
 * load reads for a title does not carry half a megabyte of image with it.
 *
 * Nothing here decodes it, exactly as with `account_avatar`: the browser resizes
 * a raster to `ICON_PIXELS` before sending and an SVG is stored as authored, so
 * the content type is what the uploader claimed and the bytes are served back
 * with it. The route that serves them is what makes that safe to do.
 */
export const installationIcon = sqliteTable(
  'installation_icon',
  {
    id: text('id').notNull(),
    image: blob('image', { mode: 'buffer' }).notNull(),
    content_type: text('content_type').notNull(),
    updated_at: text('updated_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    check('installation_icon_singleton_check', sql`${table.id} = 'installation'`),
    check('installation_icon_type_check', oneOf(table.content_type, ICON_TYPES)),
  ],
)

/**
 * The wide picture a link to this installation shows, and the homepage's own banner
 * (#306).
 *
 * Beside `installation_icon` rather than in it: a square logo a home screen installs
 * and a 1200 × 630 photograph a crawler draws are two images with nothing but an owner
 * in common. No `content_type` — a banner is a JPEG and can be nothing else.
 */
export const installationBanner = sqliteTable(
  'installation_banner',
  {
    id: text('id').notNull(),
    image: blob('image', { mode: 'buffer' }).notNull(),
    updated_at: text('updated_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    check('installation_banner_singleton_check', sql`${table.id} = 'installation'`),
  ],
)

/**
 * Where this installation posts from, when somebody has said (#30).
 *
 * Its own singleton table rather than columns on `installation` for the reason the
 * icon has one: that row is read for a title on nearly every page load, and an SMTP
 * password is not something to carry along on each of them. No row at all is the
 * ordinary state — nothing in this app requires email, and nothing fails without it.
 *
 * The password is stored as given. There is nothing else it could be: SMTP AUTH
 * sends the password itself, so a digest would be a password this app could not use.
 * It is the same class of secret as `vapid_private_key`, kept safe by the volume
 * rather than by the column.
 */
export const mailSetting = sqliteTable(
  'mail_setting',
  {
    id: text('id').notNull(),
    host: text('host').notNull(),
    port: integer('port').notNull(),
    /** Implicit TLS from the first byte — port 465. STARTTLS needs no flag. */
    secure: integer('secure', { mode: 'boolean' }).notNull(),
    /** Empty for a relay that authenticates by network rather than by password. */
    username: text('username').notNull(),
    password: text('password').notNull(),
    from_email: text('from_email').notNull(),
    /** Empty falls back to what the installation calls itself. */
    from_name: text('from_name').notNull(),
    updated_at: text('updated_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    check('mail_setting_singleton_check', sql`${table.id} = 'installation'`),
    check('mail_setting_port_check', sql`${table.port} BETWEEN 1 AND 65535`),
    check('mail_setting_host_check', sql`length(trim(${table.host})) > 0`),
    check('mail_setting_from_check', sql`length(trim(${table.from_email})) > 0`),
  ],
)

/** A single burn. Never assume there is only one — the whole point is recurrence. */
export const event = sqliteTable(
  'event',
  {
    id: text('id').notNull(),
    name: text('name').notNull(),
    slug: text('slug').notNull().unique(),
    start_date: text('start_date').notNull(),
    end_date: text('end_date').notNull(),
    start_time: text('start_time').notNull().default('00:00'),
    end_time: text('end_time').notNull().default('23:59'),
    /** Where this one is held. Public: the homepage says it and the share card maps it. */
    location: text('location').notNull().default(''),
    welcome_markdown: text('welcome_markdown').notNull().default(''),
    /** How to pay for this burn. Shown to whoever has not, on the Members page. */
    payment_info_markdown: text('payment_info_markdown').notNull().default(''),
    /** What replaces it once the burn is full — how a place is handed over (#23). */
    transfer_info_markdown: text('transfer_info_markdown').notNull().default(''),
    /** What the Meal page says above its table. Markdown, and any member may rewrite it. */
    meal_intro_markdown: text('meal_intro_markdown').notNull().default(''),
    member_cap: integer('member_cap').notNull(),
    created_at: text('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    // Mirrors `withEventDateOrder` in the shared schemas. Dates are fixed-width
    // ISO, so a string comparison is chronological here.
    check('event_start_date_check', isIsoDate(table.start_date)),
    check('event_end_date_check', isIsoDate(table.end_date)),
    // The pair, not just the days: a one-day burn can be 10:00 to 22:00, or
    // wrongly 22:00 to 10:00. Times only decide it when the days are equal —
    // across days an earlier clock time is ordinary. Both are fixed-width
    // strings, so the comparison is sound for the same reason the dates are.
    check(
      'event_date_order_check',
      sql`${table.end_date} > ${table.start_date} or (${table.end_date} = ${table.start_date} and ${table.end_time} >= ${table.start_time})`,
    ),
    check('event_start_time_check', isClockTime(table.start_time)),
    check('event_end_time_check', isClockTime(table.end_time)),
    check('event_member_cap_check', sql`${table.member_cap} > 0`),
  ],
)

/**
 * The per-event lists a member picks from: where to sleep, what to help with.
 *
 * Per event, unlike `form_question`, because these are the answers that change with
 * the site and the year — what is available at this burn, not what the community
 * asks once. `place` joined them in #156, for the same reason.
 */
export const eventOption = sqliteTable(
  'event_option',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    kind: text('kind', { enum: eventOptionKinds }).notNull(),
    // Not unique: reordering swaps positions, and a transient collision mid-swap
    // must not be rejected.
    order: integer('order').notNull(),
    label: text('label').notNull(),
    /** How many fit, or null for no limit. Only lodging uses it. */
    capacity: integer('capacity'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('event_option_event_kind_idx').on(table.event_id, table.kind, table.order),
    check('event_option_kind_check', oneOf(table.kind, eventOptionKinds)),
    check('event_option_order_check', sql`${table.order} >= 0`),
    check('event_option_label_check', sql`length(trim(${table.label})) > 0`),
    // Null means no limit; zero would mean the option exists and nobody fits,
    // which is a deleted option spelled confusingly.
    check('event_option_capacity_check', sql`${table.capacity} is null or ${table.capacity} > 0`),
  ],
)

/**
 * The application form's questions — **one central set**, not one per event.
 *
 * Rows, not code: admins retune these between burns, so adding, editing or
 * reordering a question must never require a redeploy.
 *
 * Someone applies to join the community once, the way they would be admitted to a
 * Discord server; coming to a particular burn is a separate act afterwards. An
 * `event_id` here would have made the same person answer the same questions again
 * for every burn, and made "the questions" ambiguous the moment two events existed.
 */
export const formQuestion = sqliteTable(
  'form_question',
  {
    id: text('id').notNull(),
    // Not unique: reordering swaps positions, and a transient collision
    // mid-swap must not be rejected by the database.
    order: integer('order').notNull(),
    type: text('type', { enum: formQuestionTypes }).notNull(),
    label: text('label').notNull(),
    help_text: text('help_text'),
    required: integer('required', { mode: 'boolean' }).notNull().default(false),
    /** Reserved for future select/radio types; no question type consumes it yet. */
    options: text('options', { mode: 'json' }).$type<string[] | null>(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('form_question_order_idx').on(table.order),
    check('form_question_type_check', oneOf(table.type, formQuestionTypes)),
    check('form_question_order_check', sql`${table.order} >= 0`),
    // SQLite has no boolean type, so without this the column accepts 7.
    check('form_question_required_check', sql`${table.required} in (0, 1)`),
    // `required` is not a free choice for the two tick-box types, and the rule is
    // here rather than only in the API: `required` has `.default(false)`, so an
    // insert that simply omits it — a migration, a manual fix, a backfill —
    // produces the contradictory row without ever touching a Zod schema. Same
    // argument as `oneOf` above, and generated the same way so the database is not
    // the one enforcement site holding its own copy of the rule.
    ...tickBoxChecks(table),
  ],
)

/**
 * The allergy vocabulary everybody picks from (#254).
 *
 * Global rather than per burn, like `form_question` and unlike `event_option`: what
 * somebody cannot eat is a fact about them, not about one gathering, and a per-burn
 * list would mean re-ticking it every time.
 *
 * Rows rather than an enum so an admin adds one without a deploy — the same argument
 * the application form makes. The free text on `account` stays beside these as
 * "Other", because a list is never complete.
 */
export const allergyItem = sqliteTable(
  'allergy_item',
  {
    id: text('id').notNull(),
    // Not unique: reordering swaps positions, and a transient collision mid-swap
    // must not be rejected.
    order: integer('order').notNull(),
    label: text('label').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('allergy_item_order_idx').on(table.order),
    check('allergy_item_order_check', sql`${table.order} >= 0`),
    check('allergy_item_label_check', sql`length(trim(${table.label})) > 0`),
  ],
)

/**
 * What one person cannot eat, as ticks against that list.
 *
 * On the `account`, not an `attendance`: allergies describe a human, and held per
 * burn a correction would leave every other burn wrong — the same reason
 * `allergies_notes` lives there.
 *
 * **No `onDelete` on the item**, unlike `attendance_helping`'s option. SQLite refuses
 * to remove an item somebody has ticked, and `allergies.ts` turns that into a 409 an
 * admin can act on. Cascading would silently drop a row that exists to keep somebody
 * safe; renaming is what an admin actually wants when a label is wrong.
 */
export const accountAllergy = sqliteTable(
  'account_allergy',
  {
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    item_id: text('item_id')
      .notNull()
      .references(() => allergyItem.id),
  },
  (table) => [primaryKey({ columns: [table.account_id, table.item_id] })],
)

/**
 * Somewhere a dream can happen — **per event**, seeded from a previous burn.
 *
 * The venue outlives the burn but the set in use does not: some spots are
 * summer-only, and a large event tent is there some years and not others. One
 * central list meant every schedule grid carried lanes that do not exist at this
 * burn, and the grid is the thing the list exists to build (#156).
 */
export const place = sqliteTable(
  'place',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    // Not unique, for the same reason as `form_question.order`: reordering swaps
    // positions, and a transient collision mid-swap must not be rejected.
    order: integer('order').notNull(),
    name: text('name').notNull(),
    emoji: text('emoji').notNull(),
    color: text('color', { enum: placeColors }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('place_event_order_idx').on(table.event_id, table.order),
    check('place_color_check', oneOf(table.color, placeColors)),
    check('place_order_check', sql`${table.order} >= 0`),
    check('place_name_check', sql`length(trim(${table.name})) > 0`),
    check('place_emoji_check', sql`length(trim(${table.emoji})) > 0`),
  ],
)

/** A membership application submitted through the public form. */
export const application = sqliteTable(
  'application',
  {
    id: text('id').notNull(),
    /**
     * The questions as they were worded when asked, each beside its answer.
     *
     * A snapshot rather than references, because the questions are rows an
     * admin edits between burns: an answer keyed only by `form_question.id`
     * either ends up filed under wording nobody was shown, or under a question
     * that has since been deleted and cannot be labelled at all.
     *
     * The type is imported, not restated, so this column and what the API
     * validates cannot drift — and the insert needs no cast to compile.
     */
    answers: text('answers', { mode: 'json' }).$type<StoredAnswers>().notNull(),
    status: text('status', { enum: applicationStatuses }).notNull().default('pending'),
    applicant_name: text('applicant_name').notNull(),
    /**
     * Where the invite goes, and the address the account is made under (#30).
     *
     * Was `applicant_contact`, a free-text "how can we reach you" that held phone
     * numbers and Discord handles as often as addresses. No CHECK: rows written
     * before it was an address still hold whatever they held, and a constraint the
     * existing data fails is a migration that cannot run.
     */
    applicant_email: text('applicant_email').notNull(),
    submitted_at: text('submitted_at').notNull(),
    decided_at: text('decided_at'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('application_status_idx').on(table.status),
    check('application_status_check', oneOf(table.status, applicationStatuses)),
  ],
)

/** A login identity. Password and passkeys both hang off this. */
export const account = sqliteTable(
  'account',
  {
    id: text('id').notNull(),
    /**
     * Lowercase ASCII — enforced by the CHECK below, not merely intended.
     *
     * SQLite's UNIQUE on TEXT uses BINARY collation, so on its own it would
     * make `admin@example.org` and `Admin@Example.org` two different accounts
     * for one human, each with its own passkeys, roles and memberships.
     *
     * The guarantee is ASCII-only, because SQLite's `lower()` is: `Å@x.org`
     * satisfies the CHECK unchanged and can coexist with `å@x.org`. Narrow in
     * practice — a non-ASCII local part needs SMTPUTF8, and domains arrive
     * punycoded — but it is exactly the case this CHECK cannot backstop. So
     * **the application must still normalise with JS `toLowerCase()` before
     * writing or looking up**; do not read this constraint as making an
     * exact-match lookup unconditionally safe.
     */
    email: text('email').notNull().unique(),
    /** Nullable: a passkey-only account is legitimate. */
    password_hash: text('password_hash'),
    /**
     * Who this is, and how to reach them — the things that describe a person
     * rather than a stay.
     *
     * Nullable because an account can exist before anyone has filled them in:
     * the bootstrap admin is created from the CLI with an email and nothing
     * else. Redemption sets them, and #18 lets a member edit them afterwards.
     */
    name: text('name'),
    contact: text('contact'),
    /**
     * Free text — "gluten", "sensitive to red lentils". Never a fixed list.
     *
     * Here rather than per burn on purpose: held per attendance it meant a copy
     * for every burn someone came to, and correcting one left the others wrong —
     * on data that exists to keep people safe.
     */
    allergies_notes: text('allergies_notes'),
    /**
     * The invite this account was redeemed from, or null for one created from
     * the CLI.
     */
    // Return type annotated because `account` and `invite_token` reference each
    // other — `created_by` points back here — and TypeScript cannot infer either
    // in a cycle.
    invite_token_id: text('invite_token_id').references((): AnySQLiteColumn => inviteToken.id),
    created_at: text('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    check('account_email_lowercase_check', sql`${table.email} = lower(${table.email})`),
    // What makes an invite single-use for as long as the account exists.
    // Partial, because NULLs compare distinct in SQLite and every CLI-created
    // account carries none. Delete the account and this stops objecting, so
    // redemption also stamps `used_at` in the same transaction — neither
    // mechanism is enough alone.
    uniqueIndex('account_invite_token_idx')
      .on(table.invite_token_id)
      .where(sql`${table.invite_token_id} is not null`),
  ],
)

/**
 * A registered WebAuthn credential. An account may have several, or none.
 *
 * Passkeys and passwords coexist rather than replacing each other (#9): the same
 * account may hold both, either, and — for a passkey-only account —
 * `account.password_hash` is null. What must never happen is neither, which is
 * why removing the last passkey off an account with no password is refused.
 */
export const passkey = sqliteTable(
  'passkey',
  {
    id: text('id').notNull(),
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    credential_id: text('credential_id').notNull().unique(),
    /** COSE public key, base64url. Not a secret; verifying a signature needs it. */
    public_key: text('public_key').notNull(),
    /** Signature counter, for cloned-authenticator detection. */
    counter: integer('counter').notNull().default(0),
    /**
     * How the browser said it reaches this authenticator — `internal`, `usb`,
     * `hybrid`. Comma-separated, and null when it said nothing.
     *
     * Only a hint, and only used to build `excludeCredentials`, so an unknown
     * value is dropped rather than refused: the transport list is not what makes
     * a credential usable.
     */
    transports: text('transports'),
    /** What the member calls it, so a list of three is possible to act on. */
    label: text('label').notNull(),
    created_at: text('created_at').notNull(),
    /** Null until it has signed somebody in. */
    last_used_at: text('last_used_at'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('passkey_account_idx').on(table.account_id),
    check('passkey_counter_check', sql`${table.counter} >= 0`),
  ],
)

/**
 * One outstanding ceremony, so an assertion cannot be replayed.
 *
 * A row rather than a signed cookie because single-use is the property that
 * matters and only storage gives it: a signed challenge is replayable for as long
 * as it is valid, and defeating replay is what a challenge is *for*. Deleted when
 * it is consumed, and the expired ones are swept whenever a new one is minted —
 * at 42 members that is cheaper than anything scheduled.
 *
 * `account_id` is null for a login ceremony, where nobody has said who they are
 * yet; a registration challenge carries the account that asked for it, and is
 * refused if a different one comes back with it.
 */
export const webauthnChallenge = sqliteTable('webauthn_challenge', {
  challenge: text('challenge').primaryKey(),
  account_id: text('account_id').references(() => account.id, { onDelete: 'cascade' }),
  expires_at: text('expires_at').notNull(),
})

/** Coarse access level. No fine-grained permissions in v1. */
export const accountRole = sqliteTable(
  'account_role',
  {
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    role: text('role', { enum: accountRoles }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.account_id, table.role] }),
    check('account_role_check', oneOf(table.role, accountRoles)),
  ],
)

/**
 * A single-use invitation to join the community.
 *
 * Both membership paths converge here: approving an application mints one with
 * `application_id` set, and an admin direct invite mints one with it null.
 *
 * No `event_id`. You are let into the community, not into a burn — the
 * application carries no event either — and which burns someone then comes to is
 * a separate decision they make each time.
 */
export const inviteToken = sqliteTable(
  'invite_token',
  {
    id: text('id').notNull(),
    /**
     * SHA-256 of the invite token, never the token itself.
     *
     * The token is CSPRNG-random and unguessable, shown once in the link the
     * admin copies, and then only its digest is kept. Storing it in the clear
     * would make the SQLite file the secret: a leaked backup, or a stray copy
     * of the Docker volume, would hand out every unexpired invite verbatim.
     *
     * Lookup is by exact match on the digest, so this costs nothing
     * structurally. A plain SHA-256 is sufficient and no KDF is needed —
     * unguessable input means there is no dictionary to run.
     */
    token_hash: text('token_hash').notNull().unique(),
    /** Null for an admin-created direct invite with no application behind it. */
    application_id: text('application_id').references(() => application.id, { onDelete: 'set null' }),
    expires_at: text('expires_at').notNull(),
    /**
     * Stamped on redemption, for display and auditing.
     *
     * This is a record of redemption, not the thing preventing a second one —
     * inserting an account against an already-stamped token is accepted here.
     * `account_invite_token_idx` is what actually enforces single use.
     */
    used_at: text('used_at'),
    /**
     * The admin who minted this invite.
     *
     * No `onDelete`, so SQLite's default NO ACTION applies and an account that
     * has issued invites cannot be deleted. Deliberate: erasing who let whom in
     * would quietly rewrite the record of how the group formed. The same
     * applies to `attendance.account_id`. It does mean "delete my account" has no
     * answer yet — see #35, which owns that decision.
     *
     * NO ACTION rather than RESTRICT matters here: it is checked at the end of
     * the statement, not immediately, which is what lets an `event` delete
     * cascade through its attendances in one go without tripping over this
     * edge mid-cascade.
     */
    created_by: text('created_by')
      .notNull()
      .references(() => account.id),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    // One invite per application, so an approved application can only ever
    // become one membership. Without this, a double-clicked Approve or a
    // retried request mints two invites for the same application, and since
    // single use is keyed on the token, each redeems into a separate account:
    // one application, two humans.
    //
    // The application can win this race on its own — approving can `UPDATE ...
    // WHERE status = 'pending'` and check the row count — but the same argument
    // used for `account_invite_token_idx` applies: an invariant this
    // load-bearing should not depend on every future caller getting a
    // transaction right.
    //
    // Partial, because NULLs compare distinct in SQLite: direct admin invites
    // carry no application and must stay unconstrained.
    uniqueIndex('invite_token_application_idx')
      .on(table.application_id)
      .where(sql`${table.application_id} is not null`),
  ],
)

// The migrations introducing this table are safe only because both `member` and
// `session` are empty everywhere. `DROP TABLE member` discards rows rather than
// moving them, and the `session` rebuild makes `host_account_id` NOT NULL while
// backfilling nothing — either would fail or lose data against a populated
// database. Nothing outside tests has ever written either table, which is what
// makes that acceptable here and is not a precedent for the next rebuild.

/**
 * One person's participation in one burn.
 *
 * Created when someone marks their intention to come (#76), which is a separate
 * act from being in the community: you are approved once, then decide burn by
 * burn. Everything here is about that stay — when they arrive, where they sleep,
 * what they will help with, and whether they have paid.
 */
export const attendance = sqliteTable(
  'attendance',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    account_id: text('account_id')
      .notNull()
      .references(() => account.id),
    /** When they said they were coming. The member list is ordered by it (#79). */
    joined_at: text('joined_at').notNull(),
    arrival_date: text('arrival_date'),
    departure_date: text('departure_date'),
    /**
     * Which `event_option` they picked to sleep in, or null for not said.
     *
     * Free text until the per-event lists existed. The options still differ per
     * event and per site and an admin still adds one without a deploy — they
     * are rows now — and an id is what lets anyone count who is sleeping where.
     *
     * No `onDelete`: removing somewhere people are already sleeping is refused
     * rather than silently unbooking them, the same as a place a dream stands in.
     * `event-options.ts` turns the refusal into a 409.
     */
    lodging_option_id: text('lodging_option_id').references(() => eventOption.id),
    /**
     * Something to help with that the list does not have.
     *
     * Beside the ticked options rather than instead of them: the point of the
     * list is counting, and the point of this is that a list is never complete.
     */
    helping_other: text('helping_other'),
    notes: text('notes'),
    /** Admin-set only. Members can read their own status but never write it. */
    payment_status: text('payment_status', { enum: paymentStatuses }).notNull().default('unpaid'),
    payment_date: text('payment_date'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    // One attendance per person per burn, which is what makes opting in twice a
    // no-op rather than a second row.
    uniqueIndex('attendance_event_account_idx').on(table.event_id, table.account_id),
    check('attendance_arrival_date_check', isIsoDate(table.arrival_date)),
    check('attendance_departure_date_check', isIsoDate(table.departure_date)),
    check('attendance_payment_date_check', isIsoDate(table.payment_date)),
    check(
      'attendance_stay_order_check',
      sql`${table.arrival_date} is null or ${table.departure_date} is null
          or ${table.departure_date} >= ${table.arrival_date}`,
    ),
    check('attendance_payment_status_check', oneOf(table.payment_status, paymentStatuses)),
  ],
)

/**
 * What one member ticked on the helping-out list.
 *
 * A row per choice rather than a JSON array on `attendance`: the whole reason the
 * list exists is so an admin can count who is up for the kitchen, and counting
 * inside a JSON column is the thing that gets rewritten later.
 *
 * Both sides cascade. Withdrawing from a burn takes the ticks with it, and so does
 * an admin removing an option — unlike lodging, where a bed someone is in must
 * not vanish underneath them. Nobody is displaced by "kitchen" ceasing to be
 * offered.
 */
export const attendanceHelping = sqliteTable(
  'attendance_helping',
  {
    attendance_id: text('attendance_id')
      .notNull()
      .references(() => attendance.id, { onDelete: 'cascade' }),
    option_id: text('option_id')
      .notNull()
      .references(() => eventOption.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.attendance_id, table.option_id] })],
)

/**
 * A "dream" — a member-offered workshop, ceremony or happening.
 *
 * Named `session` per the original data model. Unrelated to login sessions,
 * which are cookie-based and have no table.
 *
 * A null time slot means offered-but-not-yet-scheduled, which is the normal
 * state right up until the burn — not an error.
 */
export const session = sqliteTable(
  'session',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    /**
     * Who runs it. Null until somebody is handed it, which is how most start.
     *
     * An `attendance` like the two tables below, and for the same reason: only
     * somebody coming can run it, and leaving the burn empties the spot here without
     * any route having to remember to. It was an `account` until #23, where the rule
     * became that leaving takes you off everything — a facilitator left behind was
     * the one place that did not hold.
     *
     * `set null` rather than cascade: the dream survives its facilitator going, and
     * the vacancy is takeable from the schedule.
     */
    facilitator_attendance_id: text('facilitator_attendance_id').references(() => attendance.id, {
      onDelete: 'set null',
    }),
    description: text('description').notNull().default(''),
    /**
     * Whether placing it in the grid leaves it behind to place again.
     *
     * Dropping one writes a copy with this off, so the check-in becomes four
     * mornings. No back-reference to the original: each morning is edited on its own.
     */
    repeatable: integer('repeatable', { mode: 'boolean' }).notNull().default(false),
    time_slot_start: text('time_slot_start'),
    time_slot_end: text('time_slot_end'),
    /**
     * Which lane the dream sits in. Null while it is only offered.
     *
     * No `onDelete`, so SQLite refuses to remove a place that still has dreams
     * in it rather than quietly unscheduling them — `places.ts` turns that into
     * a 409 the admin can act on.
     */
    place_id: text('place_id').references(() => place.id),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('session_event_slot_idx').on(table.event_id, table.time_slot_start),
    // Mirrors `withValidTimeSlot`: a slot is both ends or neither. The
    // ordering half of that rule is not expressible here — comparing ISO
    // timestamps needs instant semantics, not SQLite string comparison — so it
    // stays in the Zod schema. Noted so the asymmetry does not read as an
    // oversight.
    check(
      'session_slot_whole_check',
      sql`(${table.time_slot_start} is null) = (${table.time_slot_end} is null)`,
    ),
  ],
)

/**
 * One browser's permission to be notified — a device, not a person.
 *
 * An admin with a laptop and a phone has two rows, so a notification reaches
 * whichever they are looking at. Keyed by `endpoint`, which is the push service's
 * own URL for that browser instance and is what makes re-subscribing idempotent.
 *
 * `p256dh` and `auth` are the browser's public key and shared secret. They are what
 * the payload is encrypted to, so a push service relays a notification it cannot
 * read — which is the only reason it is acceptable to route member business through
 * Google's or Mozilla's infrastructure at all.
 *
 * Cascades with the account, so a deleted one leaves no live subscription behind.
 * Losing the `admin` role stops the notifications too, but by a different
 * mechanism — `notifyAdmins` joins through `account_role` — and the row itself
 * survives a demotion, ready if the role comes back.
 */
export const pushSubscription = sqliteTable(
  'push_subscription',
  {
    id: text('id').notNull(),
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    endpoint: text('endpoint').notNull(),
    p256dh: text('p256dh').notNull(),
    auth: text('auth').notNull(),
    created_at: text('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    // One row per browser. Subscribing twice from the same browser is the ordinary
    // case — a page reload does it — and has to update rather than accumulate.
    uniqueIndex('push_subscription_endpoint_idx').on(table.endpoint),
    index('push_subscription_account_idx').on(table.account_id),
  ],
)

/**
 * A lead role for one burn — the spreadsheet's roles tab.
 *
 * Per event, because who leads the sauna is a fact about this burn rather than
 * about the community. A new burn copies the definitions from a previous one, the
 * way `event_option` is set up fresh each time and #156 will do for places.
 *
 * **Any approved member may add, change or remove one**, staffed or not. That is
 * a deliberate divergence from every other structural edit being admin-only: these
 * are co-created events, and at 42 people trust is the mechanism. There is no undo,
 * which is the accepted cost.
 *
 * The lead is an `attendance`, not an `account`. That says two things at once: only
 * someone coming to this burn can lead something at it, and withdrawing vacates
 * whatever they held rather than leaving a name on a role nobody can reach.
 */
export const leadRole = sqliteTable(
  'lead_role',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    /** Why the role exists. Markdown, like every longer field a member writes. */
    purpose: text('purpose').notNull(),
    /** What doing it involves. Markdown. */
    tasks: text('tasks').notNull(),
    effort_before: text('effort_before', { enum: effortLevels }).notNull(),
    effort_during: text('effort_during', { enum: effortLevels }).notNull(),
    effort_after: text('effort_after', { enum: effortLevels }).notNull(),
    /**
     * How many people are wanted *besides* the lead. Zero means lead-only.
     *
     * Advisory, not a cap: the page shows "2 of 4 wanted" and never refuses
     * somebody who offers. A bed is finite; a pair of hands is not.
     */
    team_size_wanted: integer('team_size_wanted').notNull(),
    /** Vacant until somebody takes it. Cleared if they withdraw from the burn. */
    lead_attendance_id: text('lead_attendance_id').references(() => attendance.id, {
      onDelete: 'set null',
    }),
    created_at: text('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('lead_role_event_idx').on(table.event_id),
    check('lead_role_title_check', sql`length(trim(${table.title})) > 0`),
    check('lead_role_team_size_check', sql`${table.team_size_wanted} >= 0`),
    // Generated from the shared vocabulary, so the database is not holding its own
    // copy of the rule — the same argument `place.color` and `form_question.type`
    // make.
    check('lead_role_effort_before_check', oneOf(table.effort_before, effortLevels)),
    check('lead_role_effort_during_check', oneOf(table.effort_during, effortLevels)),
    check('lead_role_effort_after_check', oneOf(table.effort_after, effortLevels)),
  ],
)

/**
 * Somebody on a role's team, besides its lead.
 *
 * An `attendance` for the same reason the lead is one: only someone coming can be
 * on a team, and withdrawing takes them off it. A person may be on several teams
 * and may lead one while helping on another.
 */
export const leadRoleMember = sqliteTable(
  'lead_role_member',
  {
    role_id: text('role_id')
      .notNull()
      .references(() => leadRole.id, { onDelete: 'cascade' }),
    attendance_id: text('attendance_id')
      .notNull()
      .references(() => attendance.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.role_id, table.attendance_id] })],
)

/**
 * Somebody who will help run a dream.
 *
 * An `attendance` for the same reason a role's team is: only somebody coming can
 * carry the cushions, and withdrawing takes them off what they had offered to help
 * with rather than leaving a name nobody can reach.
 */
export const sessionHelper = sqliteTable(
  'session_helper',
  {
    session_id: text('session_id')
      .notNull()
      .references(() => session.id, { onDelete: 'cascade' }),
    attendance_id: text('attendance_id')
      .notNull()
      .references(() => attendance.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.session_id, table.attendance_id] })],
)

/**
 * One ❤️‍🔥 — somebody saying they want this dream to happen.
 *
 * A row per person rather than a counter column: the primary key is then the whole
 * "one each" rule, and the number is derived on every read rather than kept in step.
 */
export const sessionSupport = sqliteTable(
  'session_support',
  {
    session_id: text('session_id')
      .notNull()
      .references(() => session.id, { onDelete: 'cascade' }),
    attendance_id: text('attendance_id')
      .notNull()
      .references(() => attendance.id, { onDelete: 'cascade' }),
  },
  (table) => [primaryKey({ columns: [table.session_id, table.attendance_id] })],
)

/**
 * One recurring slot in the kitchen's day — `Lunch 13:00`, `Morning cleanup 9:00`.
 *
 * Per burn, and rarely touched once set: the slots are the burn's shape, like its
 * dates. What they generate is not stored — see `meal_role` for why.
 */
export const mealSlot = sqliteTable(
  'meal_slot',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    // Not unique: reordering swaps positions, and a transient collision mid-swap
    // must not be rejected.
    order: integer('order').notNull(),
    label: text('label').notNull(),
    /** `HH:MM`, fixed width, so the CHECK and the sort can both treat it as a string. */
    at: text('at').notNull(),
    kind: text('kind', { enum: mealSlotKinds }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('meal_slot_event_idx').on(table.event_id, table.order),
    check('meal_slot_order_check', sql`${table.order} >= 0`),
    check('meal_slot_label_check', sql`length(trim(${table.label})) > 0`),
    check('meal_slot_at_check', isClockTime(table.at)),
    check('meal_slot_kind_check', oneOf(table.kind, mealSlotKinds)),
  ],
)

/**
 * One sitting — Monday's lunch, Saturday's dinner.
 *
 * **Generated from the slots, not derived from them.** A derived meal is identical to
 * its template forever: no postponing Saturday's dinner an hour, no dropping lunch on
 * the day everybody leaves, no adding a late supper. Generating writes rows an
 * admin can then change one at a time, and every change is a visible edit rather
 * than a rule somewhere that has to be read to be understood.
 *
 * The slot's values are **copied**, and there is no link back to it. Renaming a slot
 * afterwards leaves the meals it already made alone, which is the same call the
 * repeatable dream makes about its copies — an instance edited on its own is the
 * point, and a parent link would only be something to keep consistent.
 */
export const meal = sqliteTable(
  'meal',
  {
    id: text('id').notNull(),
    event_id: text('event_id')
      .notNull()
      .references(() => event.id, { onDelete: 'cascade' }),
    /** `YYYY-MM-DD`. */
    date: text('date').notNull(),
    /** `HH:MM`, fixed width, so the CHECK and the sort can both treat it as a string. */
    at: text('at').notNull(),
    label: text('label').notNull(),
    kind: text('kind', { enum: mealSlotKinds }).notNull(),
    /** The sheet's "Food idea?" column. Optional, and nobody is bound by it. */
    food_idea: text('food_idea').notNull().default(''),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('meal_event_idx').on(table.event_id, table.date, table.at),
    // What makes generating safe to run again: it fills in what is missing and
    // touches nothing else, so adding a slot or extending the burn is one click and
    // never a duplicate. Two lunches on one day is a mistake, not a plan.
    uniqueIndex('meal_event_date_label_idx').on(table.event_id, table.date, table.label),
    check('meal_label_check', sql`length(trim(${table.label})) > 0`),
    check('meal_at_check', isClockTime(table.at)),
    check('meal_kind_check', oneOf(table.kind, mealSlotKinds)),
    check('meal_date_check', sql`${table.date} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  ],
)

/**
 * Somebody on one meal — its lead, a helper, or on the cleanup crew.
 *
 * An `attendance` for the reason a role's team is one: only somebody coming can cook,
 * and withdrawing takes them off everything they had signed up for.
 *
 * The primary key is the whole "once each" rule. A member may be a helper *and* on
 * cleanup for the same meal — different roles, different rows — but not twice over.
 */
export const mealRole = sqliteTable(
  'meal_role',
  {
    meal_id: text('meal_id')
      .notNull()
      .references(() => meal.id, { onDelete: 'cascade' }),
    attendance_id: text('attendance_id')
      .notNull()
      .references(() => attendance.id, { onDelete: 'cascade' }),
    role: text('role', { enum: mealRoles }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.meal_id, table.attendance_id, table.role] }),
    check('meal_role_role_check', oneOf(table.role, mealRoles)),
    // One lead per meal. The other two are unbounded — nothing runs out of people
    // willing to wash up, and a cap would only be something for an admin to raise.
    uniqueIndex('meal_role_lead_idx')
      .on(table.meal_id)
      .where(sql`${table.role} = 'lead'`),
  ],
)

/**
 * Somebody's picture for the circle in the corner.
 *
 * **In the database**, because the container has no writable path but the data volume
 * and `docker compose up` has to stay sufficient — the same argument that keeps the
 * VAPID keys here. A bind mount for uploads would be a second thing to back up and a
 * second thing to get wrong.
 *
 * Its own table rather than a column on `account`: avatars are tens of kilobytes and
 * `select().from(account)` is on the path of nearly every request. A blob there would
 * be read by all of them to be used by none.
 *
 * Sparse — an account without a picture has no row here, and the circle falls back to
 * initials. Every read of it is therefore a `leftJoin`.
 *
 * `updated_at` is what the URL carries as a version, so a new picture is a new URL and
 * no cache has to be persuaded. Sized down in the browser before it is sent, so
 * nothing here decodes an image — there is no image library in this process and no
 * appetite for one.
 */
export const accountAvatar = sqliteTable(
  'account_avatar',
  {
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    image: blob('image', { mode: 'buffer' }).notNull(),
    content_type: text('content_type').notNull(),
    updated_at: text('updated_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.account_id] }),
    // The three the upload route accepts. A CHECK as well, because the constraint
    // exists for writes that do not come through the API.
    check('account_avatar_type_check', oneOf(table.content_type, ['image/jpeg', 'image/png', 'image/webp'])),
  ],
)

// Deliberately no relations() / defineRelations() block.
//
// Those exist to power the relational query builder (`db.query.x.findMany({
// with: ... })`). We use explicit joins instead: the queries here are small,
// joins make the emitted SQL obvious, and it keeps our dependency on Drizzle's
// still-moving 1.0 API surface to the parts we actually need.

/**
 * One thing that happened to somebody (#248).
 *
 * A record rather than only a push message: the bell has to say what happened while
 * you were away and whether you have looked, and a push is gone the moment it is
 * dismissed. The push is a copy of this, not the other way round.
 */
export const notification = sqliteTable(
  'notification',
  {
    id: text('id').notNull(),
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    category: text('category', { enum: notificationCategories }).notNull(),
    body: text('body').notNull(),
    /** Where clicking it goes. Null for anything with no page of its own. */
    link: text('link'),
    created_at: text('created_at').notNull(),
    /** Null until the bell has been opened. What makes it go grey again. */
    seen_at: text('seen_at'),
  },
  (table) => [
    primaryKey({ columns: [table.id] }),
    index('notification_account_idx').on(table.account_id, table.created_at),
    check('notification_category_check', oneOf(table.category, notificationCategories)),
  ],
)

/**
 * A category somebody has explicitly chosen, either way.
 *
 * Was `notification_mute`, which held only the off ones — sound while every category
 * was on by default, and unable to say anything once #259 added five that are off by
 * default. A row here means "this person said", and absence means "they have not",
 * which is the only reading that works for both halves. The default lives in
 * `notificationCategoryInfo` and nothing is seeded, so an account made tomorrow still
 * gets today's defaults without a migration teaching it to.
 */
export const notificationSetting = sqliteTable(
  'notification_setting',
  {
    account_id: text('account_id')
      .notNull()
      .references(() => account.id, { onDelete: 'cascade' }),
    category: text('category', { enum: notificationCategories }).notNull(),
    /** The bell and the push, whose default is `notificationCategoryInfo`'s `on`. */
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    /**
     * Email, whose default is off for every category (#30).
     *
     * Defaulted in SQL as well as written by the route, so the migration adding it
     * does not have to decide anything for the rows already here — and so a channel
     * that reaches somebody's inbox is never switched on by an upgrade.
     */
    email: integer('email', { mode: 'boolean' }).notNull().default(false),
  },
  (table) => [
    primaryKey({ columns: [table.account_id, table.category] }),
    check('notification_setting_category_check', oneOf(table.category, notificationCategories)),
  ],
)
